Front
Chocolate-of-Evil/Blog pull request #12
Opened 2022-10-06 14:52 UTC by Chocolate-of-Evil

2022-11-14 07:49 UTC, MaximStadnikov requested changes

2022-11-14 07:49 UTC, MaximStadnikov commented on app/views/articles/index.html.erb
> +            <a href="<%= article_path(article) %>/edit">
есть более удобной url_helper - `edith_article_path(article)` и не нужно будет "лепить" ссылку из разных частей

2022-11-14 07:49 UTC, MaximStadnikov commented on app/views/drafts/index.html.erb
> +  <% @articles.reverse_each do |article| %>
а зачем тебе такой метод?

2022-11-14 07:54 UTC, Chocolate-of-Evil commented on app/views/drafts/index.html.erb
> +  <% @articles.reverse_each do |article| %>
Чтобы более новые черновики были сверху, а старые снизу

2022-11-14 07:57 UTC, MaximStadnikov commented on app/views/drafts/index.html.erb
> +  <% @articles.reverse_each do |article| %>
В таком случае тебе стоит передавать на фронт набор черновиков в уже подготовленном виде. То есть в `drafts_controller#index`. В этом тебе поможет метод `.order`. Применяется к коллекциям в таком виде: `Article.all.order(...)`. В скобках передаются параметры для сортировки. Погугли о том, как он работает

2022-11-16 08:43 UTC, MaximStadnikov approved these changes

2022-11-16 08:43 UTC, merged